```{r}
library(ggthemes)
library(scales)
library(latex2exp)
library(aricode)
library(mvtnorm)
source("./helpers.R")
```


```{r}
set.seed(2)

means <- matrix(c(c(1.5, 2),
         c(-2.5, 1),
         c(0, -1.25)), nrow = 3, ncol = 2, byrow = T)

cov_1 <- matrix(c(1, -0.4,
                  -0.4, 1), nrow=2)
cov_2 <- matrix(c(1, 0.5,
                  0.5, 1), nrow=2)
cov_3 <- matrix(c(1, 0,
                  0, 1), nrow=2)
covs <- array(c(cov_1, cov_2, cov_3), dim = c(2, 2, 3))
trial = generate_trial(3, 20, means, covs)

X <- trial$X
E <- X - trial$U
labels <- trial$labels

grid_points <- expand.grid(seq(min(X[, 1]), max(X[, 1]), 0.01), 
                           seq(min(X[, 2]), max(X[, 2]), 0.01))

density_tibble <- tibble(
  x = rep(grid_points[, 1], 3),
  y = rep(grid_points[, 2], 3),
  density = c(dmvnorm(grid_points, mean = means[1,], sigma = covs[,, 1]),
              dmvnorm(grid_points, mean = means[2,], sigma = covs[,, 2]),
              dmvnorm(grid_points, mean = means[3,], sigma = covs[,, 3])),
  label = rep(c(1, 2, 3), each = nrow(grid_points))
)

```

```{r}
expand_cluster_df <- function(ari_df) {
  ari_df |>
    rowwise() |>
    mutate(lambda = list(seq(smallest_lambda, largest_lambda, by = 0.01))) |>
    unnest(lambda) |>
    ungroup()
}

```

```{r}
gammas <- seq(0.0, 10, 0.01)

k_solutions <- tibble(
  id = 1:nrow(trial$X),
  x = trial$X[, 1],
  y = trial$X[, 2],
  lambda = 0,
  k = 0
)

k_solutions_weighted <- tibble(k_solutions)
k_solutions_weighted_unscaled <- tibble(k_solutions)

k_results <- tibble(
  k = 0,
  sse = sum((trial$X - trial$U)^2),
  lambda = 0,
  num_cluster = nrow(trial$X),
  ari = 0
)

k_results_weighted <- tibble(k_results)
k_results_weighted_unscaled <- tibble(k_results_weighted)

for(k in 1:59) {
  knn_weights <- sparse_weights(trial$X, k, 0, connected = F, scale = F)
  knn_solutions <- get_all_info(trial, knn_weights, gammas)
  
  k_solutions <- k_solutions |> bind_rows(
    inner_join(
      knn_solutions$clusterpath$solutions_df |>
        mutate(k = k),
      expand_cluster_df(knn_solutions$clusterpath$clusters_df),
      by = c("id", "lambda")
    )
  )
  
  k_results <- k_results |>
    bind_rows(inner_join(
      knn_solutions$cluster_sse |>
        mutate(k = k),
      expand_cluster_df(knn_solutions$cluster_ari),
      by = "lambda"
    ))
  
  knn_weights_kernel <- sparse_weights(trial$X, k, 1, connected = F, scale = T)
  knn_solutions_kernel <- get_all_info(trial, knn_weights_kernel, gammas)
  
  k_solutions_weighted <- k_solutions_weighted |> bind_rows(
    inner_join(
      knn_solutions_kernel$clusterpath$solutions_df |>
        mutate(k = k),
      expand_cluster_df(knn_solutions_kernel$clusterpath$clusters_df),
      by = c("id", "lambda")
    )
  )
  
  k_results_weighted <- k_results_weighted |>
    bind_rows(inner_join(
      knn_solutions_kernel$cluster_sse |>
        mutate(k = k),
      expand_cluster_df(knn_solutions_kernel$cluster_ari),
      by = "lambda"
    ))
  
  knn_weights_kernel_unscaled <- sparse_weights(trial$X, k, 1/8, connected = F, scale = F)
  knn_solutions_kernel_unscaled <- get_all_info(trial, knn_weights_kernel_unscaled, gammas)
  
  k_solutions_weighted_unscaled <- k_solutions_weighted_unscaled |> bind_rows(
    inner_join(
      knn_solutions_kernel_unscaled$clusterpath$solutions_df |>
        mutate(k = k),
      expand_cluster_df(knn_solutions_kernel_unscaled$clusterpath$clusters_df),
      by = c("id", "lambda")
    )
  )
  
  k_results_weighted_unscaled <- k_results_weighted_unscaled |>
    bind_rows(inner_join(
      knn_solutions_kernel_unscaled$cluster_sse |>
        mutate(k = k),
      expand_cluster_df(knn_solutions_kernel_unscaled$cluster_ari),
      by = "lambda"
    ))
}
```

```{r}
full_solutions <- tibble(
  id = 1:nrow(trial$X),
  x = trial$X[, 1],
  y = trial$X[, 2],
  lambda = small_lambda,
  bandwidth = -1
)

full_results <- tibble(
  bandwidth = -1,
  sse = sum((trial$X - trial$U)^2),
  lambda = 0,
  num_cluster = nrow(trial$X),
  ari = 0
)

for(bandwidth in c(seq(0, 4, 0.01), 100)) {
  full_weights <- sparse_weights(trial$X, nrow(trial$X) - 1, bandwidth, connected = F, scale = F)
  full_solutions_info <- get_all_info(trial, full_weights, gammas)
  
  full_solutions <- full_solutions |> bind_rows(
    inner_join(
      full_solutions_info$clusterpath$solutions_df |>
        mutate(bandwidth = bandwidth),
      expand_cluster_df(full_solutions_info$clusterpath$clusters_df),
      by = c("id", "lambda")
    )
  )

  full_results <- full_results |>
    bind_rows(inner_join(
      full_solutions_info$cluster_sse |>
        mutate(bandwidth = bandwidth),
      expand_cluster_df(full_solutions_info$cluster_ari),
      by = "lambda"
    ))
}
```

```{r}

ggplot(k_results, aes(x = lambda, y = sse)) +
  geom_line(aes(color = k, group = k)) +
  scale_x_continuous(trans = "log10") +
  scale_color_viridis_c()

ggplot(k_results_weighted, aes(x = lambda, y = sse)) +
  geom_line(aes(color = k, group = k)) +
  scale_x_continuous(trans = "log10") +
  scale_color_viridis_c()

ggplot(full_results, aes(x = lambda, y = sse)) +
  geom_line(aes(color = bandwidth, group = bandwidth)) +
  scale_x_continuous(trans = "log10") +
  scale_color_viridis_c()

```

```{r}
plot_solution_path <- function(points_df, solution_path_df, title = "", density_tibble = NA) {
  if(is_tibble(density_tibble)) {
    density_geom <- geom_contour(
      data = density_tibble,
      aes(x, y, z = density, color = factor(label), group = label),
      alpha = 0.5, bins = 6)
  } else {
    density_geom <- geom_blank()
  }
  ggplot(points_df) +
    density_geom +
    geom_path(data = solution_path_df, aes(x = x, y = y, group = id), alpha = 0.4) +
    geom_point(aes(x, y, shape = factor(label), fill = factor(label)), 
               size = 3, stroke = 0.75) +
    scale_shape_manual(values = 21:25) +
    scale_fill_manual(values=colorblind_pal()(3 + 1)[-1]) +
    scale_color_manual(values=colorblind_pal()(3 + 1)[-1], guide = "none") +
    labs(fill = "True Component", shape = "True Component") +
    theme_minimal() +
    theme(axis.title.x=element_blank(),
          axis.title.y=element_blank()) +
    ggtitle(title)
}

plot_solution_path_clusters <- function(points_df, solution_path_df, cluster_assignments, title = "", density_tibble = NA) {
  num_est_clusters <- length(unique(cluster_assignments$est_label))
  manual_fill <- hue_pal()(num_est_clusters)

  if(is_tibble(density_tibble)) {
    density_geom <- geom_contour(
      data = density_tibble,
      aes(x, y, z = density, color = factor(label), group = label),
      alpha = 0.5, bins = 6)
  } else {
    density_geom <- geom_blank()
  }
  
  points_df <- points_df |> inner_join(cluster_assignments, by = "id")
  
  ggplot(points_df) +
    density_geom +
    geom_path(data = solution_path_df, aes(x = x, y = y, group = id), alpha = 0.4) +
    geom_point(aes(x, y, shape = factor(label), fill = factor(est_label)), 
               size = 3, stroke = 0.75) +
    scale_shape_manual(values = 21:25) +
    scale_fill_manual(values = manual_fill) +
    scale_color_manual(values= colorblind_pal()(3 + 1)[-1], guide = "none") +
    labs(fill = "True Component", shape = "True Component") +
    guides(
      fill = guide_legend(ncol = 1, override.aes=list(color=manual_fill),
                          title = "Estimated Component", order = 0),
      shape = guide_legend(order = 1)
    ) +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank()) +
    ggtitle(title)
}

```

```{r}

best_lambda_per_k <- k_results |> group_by(k) |> slice_min(sse, with_ties = F) |> ungroup()

best_cluster_per_k <- k_results |> group_by(k) |> slice_max(ari, with_ties = F) |> ungroup()
only_best_sol <- k_solutions[, 1:5] |> semi_join(best_lambda_per_k, by = c("k", "lambda"))

only_best_sol <- tibble(
  id = 1:nrow(trial$X),
  x = trial$X[, 1],
  y = trial$X[, 2],
  lambda = small_lambda,
  k = 0
) |> rbind(only_best_sol)

plot_solution_path(knn_solutions$plot_dfs$points,
                   only_best_sol |> arrange(lambda),
                   "",
                   density_tibble = density_tibble)
# 
plot_solution_path(knn_solutions$plot_dfs$points,
                   k_solutions |> filter(lambda == .46 | (k == 0)),
                   "",
                   density_tibble = density_tibble)

plot_solution_path_clusters(knn_solutions$plot_dfs$points,
                   k_solutions |> filter(lambda == .33 | (k == 0)),
                   k_solutions |> filter(lambda == .33, k == 22) |> dplyr::select(id, est_label),
                   "",
                   density_tibble = density_tibble)

plot_solution_path_clusters(knn_solutions$plot_dfs$points,
                   k_solutions |> filter(lambda == .39 | (k == 0)),
                   k_solutions |> filter(lambda == .39, k == 20) |> dplyr::select(id, est_label),
                   "",
                   density_tibble = density_tibble)

plot_solution_path_clusters(knn_solutions$plot_dfs$points,
                   k_solutions |> filter(lambda == .88 | (k == 0)),
                   k_solutions |> filter(lambda == .88, k == 14) |> dplyr::select(id, est_label),
                   "",
                   density_tibble = density_tibble)

plot(best_lambda_per_k$k, best_lambda_per_k$lambda)
```

```{r}

best_lambda_per_k_weighted <- k_results_weighted |> group_by(k) |> slice_min(sse, with_ties = F) |> ungroup()

only_best_sol_weighted <- k_solutions_weighted |> semi_join(best_lambda_per_k_weighted, by = c("k", "lambda"))


plot_solution_path(knn_solutions_kernel$plot_dfs$points,
                   only_best_sol_weighted,
                   "",
                   density_tibble = density_tibble)

plot_solution_path(knn_solutions_kernel$plot_dfs$points,
                   k_solutions_weighted |> filter(lambda == .2 | (k == 0)),
                   "",
                   density_tibble = density_tibble)

```


```{r}

best_lambda_per_k_weighted_unscaled <- k_results_weighted_unscaled |> group_by(k) |> slice_min(sse, with_ties = F) |> ungroup()

only_best_sol_weighted_unscaled <- k_solutions_weighted_unscaled |> semi_join(best_lambda_per_k_weighted_unscaled, by = c("k", "lambda"))


plot_solution_path(knn_solutions_kernel_unscaled$plot_dfs$points,
                   only_best_sol_weighted_unscaled,
                   "",
                   density_tibble = density_tibble)

plot_solution_path(knn_solutions_kernel_unscaled$plot_dfs$points,
                   k_solutions_weighted_unscaled |> filter(lambda == .2 | (k == 0)),
                   "",
                   density_tibble = density_tibble)

plot_solution_path(knn_solutions_kernel_unscaled$plot_dfs$points,
                   k_solutions_weighted_unscaled |> filter(lambda == .5 | (k == 0)),
                   "",
                   density_tibble = density_tibble)

plot_solution_path(knn_solutions_kernel_unscaled$plot_dfs$points,
                   k_solutions_weighted_unscaled |> filter(lambda == 1 | (k == 0)),
                   "",
                   density_tibble = density_tibble)

plot_solution_path(knn_solutions_kernel_unscaled$plot_dfs$points,
                   k_solutions_weighted_unscaled |> filter(lambda == 2 | (k == 0)),
                   "",
                   density_tibble = density_tibble)
```


```{r}
best_lambda_per_bandwidth <- full_results |> group_by(bandwidth) |> slice_min(sse, with_ties = F) |> ungroup()
best_cluster_per_bandwidth <- full_results |> group_by(bandwidth) |> slice_max(ari, with_ties = F) |> ungroup()

only_best_sol_full <- full_solutions |> semi_join(best_lambda_per_bandwidth, by = c("bandwidth", "lambda"))

only_best_sol_full <- tibble(
  id = 1:nrow(trial$X),
  x = trial$X[, 1],
  y = trial$X[, 2],
  lambda = small_lambda,
  bandwidth = -1
) |> bind_rows(only_best_sol_full)

plot_solution_path(full_solutions_info$plot_dfs$points,
                   only_best_sol_full |> arrange(lambda),
                   "",
                   density_tibble = density_tibble)

plot_solution_path(full_solutions_info$plot_dfs$points,
                   full_solutions |> filter(lambda == 0.75),
                   "",
                   density_tibble = density_tibble)


ggsave(file="./figures/fully-connected-vary-bandwidth.pdf", device="pdf",
       dpi = 600,
       width = 3,
       height = 2,
       units = "in",
       scale = 2)
```
